name: update-flake-lock

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *' 
jobs:
  nix-flake-update:
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes ca-derivations
            extra-experimental-features = nix-command flakes ca-derivations
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-platforms = i686-linux aarch64-linux arm-linux
            log-lines = 25

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          inputs: odin-src ols-src

      - name: Commit back to the repository
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Auto update lockfile"
          commit_user_name: "yappaholic-bot"
          commit_user_email: "yappaholic-bot@users.noreply.github.com"
